spring:
  application:
    name: backend
  data:
    mongodb:
      uri: mongodb://localhost:27017/smart_ambulance
server:
  port: 8080

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Placeholder key
  expiration: 3600000 # 1 hour

google:
  maps:
    api-key: YOUR_GOOGLE_MAPS_API_KEY_HERE
